### ISSUE TITLE
Suggestion for change table name

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/EnterpriseAssetMaintenance#10]
Currently exist many tables with long name, i propose change the name for a better definition:

- AM_AssetMeter_Log -> **AM_AssetMeterLog**
- AM_MaintenancePattern -> **AM_Pattern**
- AM_MaintenancePattern_Task -> **AM_PatternTask**
- AM_MaintPattern_Resource -> **AM_PatternResource**
- AM_Maintenance_Task -> **AM_MaintenanceTask**
- AM_Maintenance_Resource - > **AM_MaintenanceResource**
- AM_ServiceOrder_Request -> **AM_ServiceRequest**
- AM_ServiceOrder_Task -> **AM_ServiceOrderTask**
- AM_ServiceOrder_Resource -> **AM_ServiceOrderResource**

The new table definition is more readable.

**Comment by marcalwestf** [comment]
Agree with suggestion, it makes sense and goes in line with ADEmpiere's syntax.
