### ISSUE TITLE
Remove unnecessary views 

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/EnterpriseAssetMaintenance#11]
Currently exist the follow views: 

- AM_Asset_Meter_Log_V
- AM_Assets_V
- AM_Maintenance_Calendar_V
- AM_Maintenance_Meter_V
- AM_MaintenancePattern_V
- AM_Maintenance_V
- AM_ServiceOrder_V

The views are create for PostgreSQL only, i propose remove all and create only necessary view. Also it will should create with **RV_** prefix instead **_V**  suffix

**Comment by marcalwestf** [comment]
The views were intended to serve as a way of having summary of the facts in the tables.

Perhaps a better alternative would be to have **Smart Browsers** instead of views, serving as information sources, where you can also filter.
