### ISSUE TITLE
Error when trying to run the migrate scripts (XML files)

### ISSUE THREAD

**Issue by gvilauy** [adempiere/EnterpriseAssetMaintenance#2]
I have some errors when I run the migratio script (./RUN_MigrateXML.sh).
These are the steps to reproduce this error:

1. Sincronize last version of adempiere380 hotfix 2 branch
2. Import seed data base
3. RUN migration for upgrade data base to last version (380lts-release folder)
4. At this point, everything is ok
5. Delete all files from Adempiere/migration/380lts-release
6. Copy migration files of adempiereEAM on Adempiere/migration/380lts-release
7. Run migration script again, and then these errors happens:

11:46:30.359   MMigrationStep.rollback: Migration 10 - 01 PM Asset Maintenance Module - null (D) ; Step: 10; Type: AD. successfully rolled back [1]
11:46:30.359   MMigrationStep.rollback: Migration 10 - 01 PM Asset Maintenance Module - null (D) ; Step: 10; Type: AD. successfully rolled back [1]
11:46:30.360   GridField.loadLookup: (AccessLevel) [1]
11:46:30.360   GridField.loadLookup: (AccessLevel) [1]
11:46:30.360   GridField.loadLookup: (ReplicationType) [1]
11:46:30.360   GridField.loadLookup: (ReplicationType) [1]
11:46:30.363   MMigration.syncColumn: Synchronizing column: MColumn[0-null] in table: MTable[0-null] [1]
11:46:30.363   MMigration.syncColumn: Synchronizing column: MColumn[0-null] in table: MTable[0-null] [1]
11:46:30.363   GridField.loadLookup: (AccessLevel) [1]
11:46:30.363   GridField.loadLookup: (AccessLevel) [1]
11:46:30.363   GridField.loadLookup: (ReplicationType) [1]
11:46:30.363   GridField.loadLookup: (ReplicationType) [1]
-----------> MMigration.apply: @NotFound@ @AD_Table_ID@ 0 [1]
-----------> MMigration.apply: @NotFound@ @AD_Table_ID@ 0 [1]
11:46:30.392   MMigration.updateStatus: Migration 10 - 01 PM Asset Maintenance Module - null (D)  ---> Unapplied (U) [1]
11:46:30.392   MMigration.updateStatus: Migration 10 - 01 PM Asset Maintenance Module - null (D)  ---> Unapplied (U) [1]
11:46:30.408   MMigration.updateStatus: Migration 10 - 01 PM Asset Maintenance Module - null (D)  ---> Unapplied (U) [1]
11:46:30.408   MMigration.updateStatus: Migration 10 - 01 PM Asset Maintenance Module - null (D)  ---> Unapplied (U) [1]
11:46:30.409 MigrationApply.addLog: 0 - null - null - @NotFound@ @AD_Table_ID@ 0 [1]
11:46:30.409 MigrationApply.addLog: 0 - null - null - @NotFound@ @AD_Table_ID@ 0 [1]
11:46:30.413 Msg.initMsg: Records=1429 - en_US [1]
11:46:30.413 Msg.initMsg: Records=1429 - en_US [1]
===========> MigrationApply.process: * Not found * Table 0 [1]
org.adempiere.exceptions.AdempiereException: * Not found * Table 0

Thanks.

**Comment by marcalwestf** [comment]
I tried just the xml file _10_AssetMaintenance_Tables.xml_ ; the migration script is wrong.

The script uses for the table definition fields which are not defined in ADempiere. Perhaps it was used as a seed a customized database which had them.

![20161201_error_eam_01](https://cloud.githubusercontent.com/assets/1789408/20816182/b03aef1c-b7e6-11e6-914a-094d027011ae.png)

In the case of the image depicted, the SQL for creating the table contains the following line:
 <**Data AD_Column_ID="64711" Column="SQLStatement" isNewNull="true"/**>
This is what you see in the image. It is an error.

A field named _SQLStatement_ does not exist for the table definition, at least not in the official Adempiere seed.

I deleted from _10_AssetMaintenance_Tables.xml_ all lines with 
 <**Data AD_Column_ID="64711" Column="SQLStatement" isNewNull="true"/**>

**Comment by marcalwestf** [comment]
The xml is still erroneous, because there are erros like the one in step **2260**: here both **72747** and **62199** are IDs of objects unknown to ADempiere.

![20161201_error_eam_02](https://cloud.githubusercontent.com/assets/1789408/20816569/974bb9c6-b7e8-11e6-9371-4800bc5189cb.png)

To solve this, it has to be analyzed the same way as I explain in my post before.

**Comment by marcalwestf** [comment]
....continuing
all lines like the following in creating columns must be deleted in xml file _10_AssetMaintenance_Tables.xml_ !!! 
<**Data AD_Column_ID="72747" Column="IsSecure" isNewNull="true"/**>
The reason: there is no filed named isSecure for column definition in ADempiere.

Same applies to
<**Data AD_Column_ID="62199" Column="IsAllowCopy" isNewNull="true"/**>
The reason: there is no filed named IsAllowCopy for column definition in ADempiere.

**Comment by gvilauy** [comment]
Ok, thanks Mario !!

**Comment by marcalwestf** [comment]
@gvilauy I have not seen a commit that overcomes this error.
The changes I suggest should be done before the issue is closed.

**Comment by gvilauy** [comment]
OK

**Comment by gvilauy** [comment]
Mario,
Here is the correected file.
[10_AssetMaintenance_Tables.xml.zip](https://github.com/adempiere/adempiereEAM/files/642407/10_AssetMaintenance_Tables.xml.zip)

**Comment by marcalwestf** [comment]
Additionally to Column="IsSecure" and Column="IsAllowCopy" , steps **3950** and **3970** had to be deleted in order to avoid the error.
 
 With this changes, _10_AssetMaintenance_Tables.xml_ can be loaded and applied successfully.

Still to be tested: _20_AssetMaintenance_ WindowAndMenu.xml_ , _30_AM_Module_Form_View.xml_  and _40_AM_Module_Process.xml_ .

**Comment by gvilauy** [comment]
Mario,
Here is the second corrected file.
[20_AssetMaintenance_ WindowAndMenu.xml.zip](https://github.com/adempiere/adempiereEAM/files/645783/20_AssetMaintenance_.WindowAndMenu.xml.zip)

**Comment by gvilauy** [comment]
Mario,
Here is the third corrected file.
[30_AM_Module_Form_View.xml.zip](https://github.com/adempiere/adempiereEAM/files/645951/30_AM_Module_Form_View.xml.zip)

**Comment by gvilauy** [comment]
Mario,
Here is the last corrected file.
[40_AM_Module_Process.xml.zip](https://github.com/adempiere/adempiereEAM/files/645958/40_AM_Module_Process.xml.zip)
