### ISSUE TITLE
Menu entries not displayed in menu tree

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/EnterpriseAssetMaintenance#5]
XML file  _20AssetMaintenance  WindowAndMenu.xml_ creates menu entries for windows of the EAM module like _Meter_ or _Meter Log_.

After executing the xml file, the menu table contains the entries, but they are not displayed in the tree, as  can be seen in the following image.
![20161213_menu_entry_not_displayed_in_tree](https://cloud.githubusercontent.com/assets/1789408/21167847/fe21d19a-c174-11e6-81a7-e7e60a442f3a.png)

**Comment by yamelsenih** [comment]
Hi @marcalwestf it is because translation is not added. You must run process for add missing translations
